### ISSUE TITLE
Change req:  ZOOM

### ISSUE THREAD

**Issue by dobryj** [haxko/NE3-Scope#6]
Could you please add ability to ZOOM output window?
Necessary patch is in the attachment, but better could be zoom parameter from command line.

[zoom_x1.5.diff.txt](https://github.com/haxko/NE3-Scope/files/12828497/zoom_x1.5.diff.txt)

**Comment by niyawe** [comment]
done

**Comment by dobryj** [comment]
Great! Thanks.
